# Generated by Django 3.2.13 on 2022-08-09 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0001_initial'),
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='center',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='branch_center', to='center.center'),
            preserve_default=False,
        ),
    ]
