# Generated by Django 3.2.13 on 2022-08-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_branch_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='loan',
            field=models.IntegerField(default=0),
        ),
    ]
