# Generated by Django 3.2.13 on 2022-08-09 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='title',
        ),
        migrations.AddField(
            model_name='role',
            name='owner',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='users.user'),
            preserve_default=False,
        ),
    ]
