# Generated by Django 3.2.13 on 2022-08-10 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20220810_1421'),
        ('users', '0005_remove_user_show_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='contact.contact'),
            preserve_default=False,
        ),
    ]
