# Generated by Django 3.2.13 on 2022-08-11 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_role_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.role'),
            preserve_default=False,
        ),
    ]
