# Generated by Django 3.2.13 on 2022-08-11 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20220811_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.role'),
        ),
    ]
