# Generated by Django 3.2.13 on 2022-08-13 14:49

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_center'),
        ('users', '0016_auto_20220813_1308'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth_dayofyear_internal',
        ),
        migrations.AddField(
            model_name='usergroup',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='course.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
