# Generated by Django 3.2.13 on 2022-08-13 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_remove_branch_center'),
        ('center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='branch',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='center', to='branch.branch'),
            preserve_default=False,
        ),
    ]
