# Generated by Django 3.2.13 on 2022-08-08 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0001_initial'),
        ('payment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthly_bill',
            name='center',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='monthly_bill', to='center.center'),
            preserve_default=False,
        ),
    ]
