# Generated by Django 3.2.13 on 2022-08-09 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_monthly_bill_center'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthly_bill',
            name='price',
        ),
    ]
