# Generated by Django 3.2.13 on 2022-08-10 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_remove_monthly_bill_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outcome',
            name='center',
        ),
        migrations.RemoveField(
            model_name='outcome',
            name='payment_type',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
        migrations.DeleteModel(
            name='Outcome',
        ),
    ]
