# Generated by Django 3.2.13 on 2022-08-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_payment_history_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_history',
            name='payment_number',
            field=models.CharField(blank=True, max_length=7, unique=True),
        ),
    ]
